### ISSUE TITLE
Liste des serveurs par environnement (yaml)

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#100]
Faire en sorte que la liste des serveurs disponibles sur le swagger d'API soit adapté à l'environnement

**Comment by cbriand** [comment]
[crenny35](https://github.com/crenny35) commented [9 minutes ago](https://github.com/sigrennesmetropole/api-3D/issues/94#issuecomment-1354355599)
Pour le Yaml, il faudrait tester de mettre /api dans le yaml au lieu de l'url complète vu qu'il y a un nom de domaine différent pour le serveur de test et de prod cela devrait marcher.

**Comment by crenny35** [comment]
@cbriand les deux tickets sont testables depuis l'image develop.

**Comment by cbriand** [comment]
Ca marche très bien ! Merci.
A passer dans la branche master + release

**Comment by crenny35** [comment]
Est ce que je crée une release 1.0.0 pour la fin ?

**Comment by cbriand** [comment]
Non, parce qu'on a toujours les textes de la page swagger à mettre à jour par l'équipe interne RM. Une fois que ce sera fait, on pourra lancer la release 1.0.0.
On va se contenter d'une 0.5.3 aujourd'hui.
