### ISSUE TITLE
A1 - Terrain maillé (format TIN) avec texture orthophotographie

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#20]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger le fichier "terrain maillé texturé".

Pour valider cette API, je dois pouvoir recevoir localement le fichier téléchargé représentant le terrain maillé au format TIN. L'intégrité du fichier doit pouvoir être vérifiée avec sa clé sha-1.

**Comment by cbriand** [comment]
**Recette du 17/06/2022**
- Retranscription des informations OK
- Le téléchargement du fichier fonctionne, mais ce n'est pas le bon nom de fichier (attendu : 3d_rennesmetropole_terrain_maillage.zip)

**Comment by crenny35** [comment]
Changement de la méthode de récupération du fichier pour garder le nom d'origine du fichier

**Comment by cbriand** [comment]
OK, validé
