### ISSUE TITLE
A6 - Liste des bâtiments supprimés

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#25]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger la liste des bâtiments supprimés. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir un fichier json qui liste les bâtiments qui ont été supprimés de la maquette depuis la date passée en paramètre. Si aucune date n'est passée en paramètre, alors la date de référence est le millésime de la maquette 3D.
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.

**Comment by anthalcgi** [comment]
Le filtre par bbox est-il nécessaire ? Le filtre par code Insee est possible en utilisant l'id du bâtiment mais le filtre par bbox est impossible car les attributs géographiques du bâtiment n'existent plus une fois qu'il est supprimé.

**Comment by cbriand** [comment]
En effet, dans ce cas, on ne propose pas le filtre BBox. Ce n'est pas gênant puisque cette fonction concerne principalement la mise à jour de la maquette HD offerte en téléchargement qui couvre l'ensemble du territoire métropolitain.
On garde le filtre par code insee qui peut s'avérer pratique pour certains utilisateurs.

**Comment by cbriand** [comment]
OK sur tous les filtres, sauf la date.

1 - documenter le format de date attendu en saisie :  "AAAA-MM-JJ"
2 - erreur : une variable ne semble pas définie
```
info: Appel du path /collections/deleted_building/items {"parametres":{"date":"2022-09-01"},"service":"user-service","timestamp":"2022-09-15T15:59:21.572Z"}
date_ope is not defined
```

**Comment by cbriand** [comment]
idem #26 sur la construction de la requête qui n'intègre pas la variable date

**Comment by cbriand** [comment]
KO. La requête n'est SQL n'est pas correcte, il y a un '.' en trop dans la clause FROM :
<pre>SELECT bati_id, TO_CHAR(date_ope, 'yyyy-mm-dd') AS date FROM .suivi_evolutions.v_batis_suppr WHERE LEFT(bati_id,5) LIKE '35245' ORDER BY date_ope DESC LIMIT 100000</pre>

**Comment by cbriand** [comment]
OK, ça fonctionne
