### ISSUE TITLE
A7 - Bâtiments ajoutés

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#26]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger les bâtiments ajoutés à la maquette. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir les bâtiments 3D qui viennent compléter la maquette depuis la date passée en paramètre. Si aucune date n'est passée en paramètre, alors la date de référence est le millésime de la maquette 3D.
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.

**Comment by cbriand** [comment]
Spécifications : 
Pour suivre les évolutions de la maquette 3D des bâtiments, la base de données 3dcitydb a été complétée par un schéma suivi_evolutions dans lequel on retrouve des tables et des vues qui recueillent l'historique des évolutions.
La vue **suivi_evolutions.v_batis_ajout** permet de connaitre les identifiants de bâtiments qui ont été créés depuis le dernier millésime 
L'attribut bati_id correspond à un identifiant de bâtiment référencé dans la base 3dcitydb
L'attribut date_ope correspond à la date de création du bâtiment.

A partir de ces deux attributs, l'API doit obtenir la liste des identifiants de bâtiments ajoutés depuis une date passée en paramètre. Si aucune date n'est passée en paramètre, toutes les lignes de la vue sont prises.
L'API doit ensuite retourner les objets 3D correspondant à ces identifiants de bâtiments depuis la base 3dcitydb.

**Comment by crenny35** [comment]
@cbriand , Est ce que le millésime est stocké dans la base ou doit on ajouter un paramètre de configuration pour le stocker ?
Faut il aussi comme sur l'autre API avoir un paramètre texturé (oui/non) et un autre format (gml/json) .

**Comment by sigrmed** [comment]
Non, pas de millesime stocké en base. Les modifications de bâtiments ne concernent que le millésime courant. La table de suivi de modifications sera vidé à chaque MEP d'un nouveau millesime.
Le paramètre texturé O/N n'est pas utile parce que les bâtiments ajoutés/modifiés n'auront jamais de texture.
Le paramètre de sortie gml/json est, lui, utile.

**Comment by cbriand** [comment]
Non, pas de millesime stocké en base. Les modifications de bâtiments ne concernent que le millésime courant. La table de suivi de modifications sera vidé à chaque MEP d'un nouveau millesime.
Le paramètre texturé O/N n'est pas utile parce que les bâtiments ajoutés/modifiés n'auront jamais de texture.
Le paramètre de sortie gml/json est, lui, utile.

**Comment by cbriand** [comment]
OK sur votre plateforme de recette, mais pas sur notre instance (production). Les logs montrent une erreur de requête qui laisse penser que nous ne sommes pas sur la même version de la 3dcitydb.
<pre>
error: Command failed: /etc/impexp/bin/impexp export --db-host=10.253.100.2 --db-port=5432 --db-name=3dcitydb --db-username=app_api --db-password="xxx" -o /usr/src/app/src/export/f51876e9-5e91-4f17-9e36-956b8cf366b2.cityjson --no-appearance --bbox=1330000,7203000,1368000,7246000 --sql-select="SELECT cityobject_id FROM cityobject_genericattrib WHERE gmlid in (SELECT bati_id FROM suivi_evolutions.v_batis_ajout)"
[08:19:44 ERROR] Failed to query the database.
[08:19:44 ERROR] Caused by: org.postgresql.util.PSQLException: ERREUR: la relation « cityobject_genericattrib » n'existe pas
</pre>

Notre instance 3dcitydb est en version 4.2.0 car la version 4.3.0 était incompatible avec la dernière version de l'importer/exporter en début de projet. Nous n'avons pas qualifié la compatibilité entre les nouvelles releases actuelles. La colonne cityobject_genericattrib.gmlid n'existe pas en 4.2.0

=> RM : évolution des versions 3dcitydb et importer/exporter sur notre plateforme ?

**Comment by cbriand** [comment]
Montée de version en 4.3.0 de 3dcitydb réalisée. 
La colonne cityobject_genericattrib.gmlid n'existe toujours pas en 4.3.0. La requête est fausse et ne peut pas retourner d'objet3D

La requête suivante semble plus pertinente (valable en v4.3.0 et v4.2.0 de la base)
SELECT cityobject_id
FROM citydb.cityobject_genericattrib
WHERE attrname='BUILDINGID' and strval IN (SELECT bati_id FROM suivi_evolutions.v_batis_ajout)

**Comment by cbriand** [comment]
Ca fonctionne sur la plateforme de recette CGI mais pas sur la plateforme de prod RM installée avec la release v0.4.1 => est-ce que l'évolution est bien déployée dans cette version ?

**Comment by cbriand** [comment]
Bug avéré et confirmé avec @crenny35 par échanges.
La requête produite fait toujours référence au champ gmlid qui n'existe pas dans la table cityobject_genericattrib. Par ailleurs, la requête n'est pas optimisée.

**PSEUDO-CODE DE CONSTRUCTION DE LA REQUETE :**

```
var requête  = "SELECT cityobject_id FROM citydb.cityobject_genericattrib WHERE attrname='BUILDINGID' and strval IN (SELECT bati_id FROM suivi_evolutions.v_batis_ajout 

bool where = false;
SI CODE_INSEE ALORS
    SI where ALORS
        requête += " AND ";
    SINON
        requête += "WHERE ";
        where = true;
    FIN SI
    requête += " bati_id like " + <code_insee> + "_%";
FIN SI
SI DATE ALORS
    SI where ALORS
        requête += " AND ";
    SINON
        requête += "WHERE ";
        where = true;
    FIN SI
    requête +=  "(date_ope BETWEEN + <date>+' AND now())"
FIN SI
requête += ")"
return requete
```

Les filtres bbx, startindex et limit sont gérés par options de l'importer_exporter et non pas par la requête.
Attention à bien faire apparaitre le nom des schema porteurs des tables pour que les relations ne soient pas ambigues (par défaut notre instance postgres n'accepte pas les clause FROM sans précision de schéma

**Comment by cbriand** [comment]
Mauvais copier-coller du pseudo-code sur la gestion du filtre sur date dans le fichier DataService.js définition de la const makeQueryString où la valeur de l'attribut date n'est pas intégrée dans la requête

`requete += "(date_ope BETWEEN + <date>+' AND now())"; `

**Comment by cbriand** [comment]
KO. La requête n'est SQL n'est pas correcte, il y a un '.' en trop dans la clause FROM de la sous-requête : 
<pre>"SELECT cityobject_id FROM citydb.cityobject_genericattrib WHERE attrname='BUILDINGID' and strval IN (SELECT bati_id FROM .suivi_evolutions.v_batis_ajout WHERE bati_id like '35245_%')"</pre>

**Comment by cbriand** [comment]
Ok, ça fonctionne très bien 👍
