### ISSUE TITLE
A8 - Bâtiments modifiés

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#27]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger les bâtiments modifiés depuis une date. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir les bâtiments 3D qui ont subi une modification depuis la date passée en paramètre. Si aucune date n'est passée en paramètre, alors la date de référence est le millésime de la maquette 3D.
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.

**Comment by cbriand** [comment]
Spécifications : 
Pour suivre les évolutions de la maquette 3D des bâtiments, la base de données 3dcitydb a été complétée par un schéma suivi_evolutions dans lequel on retrouve des tables et des vues qui recueillent l'historique des évolutions.
La vue **suivi_evolutions.v_batis_modif** permet de connaitre les identifiants de bâtiments qui ont subi une modification. 
L'attribut bati_id correspond à un identifiant de bâtiment référencé dans la base 3dcitydb
L'attribut date_ope correspond à la date de mise à jour du bâtiment.

A partir de ces deux attributs, l'API doit obtenir la liste des identifiants de bâtiments modifiés depuis une date passée en paramètre. Si aucune date n'est passée en paramètre, toutes les lignes de la vue sont prises.
L'API doit ensuite retourner les objets 3D correspondant à ces identifiants de bâtiments depuis la base 3dcitydb.

**Comment by cbriand** [comment]
Nom de la route à corriger : "/collections/modifed_building/items" en "/collections/**_modified_**_building/items"

**Comment by cbriand** [comment]
idem #26 : la requête utilisée avec l'importer/exporter ne fonctionne pas : 
error: Command failed: /etc/impexp/bin/impexp export --db-host=10.253.100.2 --db-port=5432 --db-name=3dcitydb --db-username=app_api --db-password="XXXX" -o /usr/src/app/src/export/8c47d4f9-cd69-435b-9f78-28e1ca02d067.cityjson --no-appearance --bbox=1330000,7203000,1368000,7246000 --sql-select="SELECT cityobject_id FROM cityobject_genericattrib WHERE gmlid in (SELECT bati_id FROM suivi_evolutions.v_batis_modif)"
[09:41:49 ERROR] Failed to query the database.
[09:41:49 ERROR] Caused by: org.postgresql.util.PSQLException: ERREUR: la relation « cityobject_genericattrib » n'existe pas

La colonne cityobject_genericattrib.gmlid n'existe pas

**Comment by cbriand** [comment]
Ca fonctionne sur la plateforme de recette CGI mais pas sur la plateforme de prod RM installée avec la release v0.4.1 => est-ce que l'évolution est bien déployée dans cette version ?

**Comment by cbriand** [comment]
Bug avéré et confirmé avec @crenny35 par échanges.
La requête produite fait toujours référence au champ gmlid qui n'existe pas dans la table cityobject_genericattrib. Par ailleurs, la requête n'est pas optimisée.

**PSEUDO-CODE DE CONSTRUCTION DE LA REQUETE :**

```
var requête  = "SELECT cityobject_id FROM citydb.cityobject_genericattrib WHERE attrname='BUILDINGID' and strval IN (SELECT bati_id FROM suivi_evolutions.v_batis_modif 

bool where = false;
SI CODE_INSEE ALORS
    SI where ALORS
        requête += " AND ";
    SINON
        requête += "WHERE ";
        where = true;
    FIN SI
    requête += " bati_id like " + <code_insee> + "_%";
FIN SI
SI DATE ALORS
    SI where ALORS
        requête += " AND ";
    SINON
        requête += "WHERE ";
        where = true;
    FIN SI
    requête +=  "(date_ope BETWEEN + <date>+' AND now())"
FIN SI
requête += ")"
return requete
```

Les filtres bbx, startindex et limit sont gérés par options de l'importer_exporter et non pas par la requête.
Attention à bien faire apparaitre le nom des schema porteurs des tables pour que les relations ne soient pas ambigues (par défaut notre instance postgres n'accepte pas les clause FROM sans précision de schéma

**Comment by cbriand** [comment]
KO. La requête n'est SQL n'est pas correcte, il y a un '.' en trop dans la clause FROM de la sous-requête : 
<pre>SELECT cityobject_id FROM citydb.cityobject_genericattrib WHERE attrname='BUILDINGID' and strval IN (SELECT bati_id FROM .suivi_evolutions.v_batis_modif WHERE bati_id like '35245_%')</pre>

**Comment by crenny35** [comment]
Est ce que les variables d'environnement on bien été renseignée comme ceci :

DB_SCHEMA_EVOLUTION=suivi_evolutions
DB_VIEW_ADDED_BUILDINGS=v_batis_ajout
DB_VIEW_MODIFIED_BUILDINGS=v_batis_modif
DB_VIEW_DELETED_BUILDINGS=v_batis_suppr

et non pas : 
DB_SCHEMA_EVOLUTION=
DB_VIEW_ADDED_BUILDINGS=suivi_evolutions.v_batis_ajout
DB_VIEW_MODIFIED_BUILDINGS=suivi_evolutions.v_batis_modif
DB_VIEW_DELETED_BUILDINGS=suivi_evolutions.v_batis_suppr

**Comment by cbriand** [comment]
OK, ça fonctionne mieux. Comme la doc d'installation n'est pas à jour, je n'aurais pas deviné l'usage de ces variables (notamment qu'il existait une nouvelle variable DB_SCHEMA_EVOLUTION). J'ai fait un nouveau ticket pour la mise à jour de la doc #79 .

**Comment by cbriand** [comment]
OK, ça marche très bien 👍
