### ISSUE TITLE
B2.a - Streaming - Bâtiments (non texturés)

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#29]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger les bâtiments sans texture. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir les bâtiments 3D.
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.
Je dois aussi pouvoir charger un bâtiment unique par son identifiant

**Comment by crenny35** [comment]
Disponible en integration

**Comment by cbriand** [comment]
En attente du ticket #66

**Comment by cbriand** [comment]
OK, validé
