### ISSUE TITLE
B2.b - Streaming - Bâtiments (texturés)

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#30]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger les bâtiments avec texture. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir les bâtiments 3D.
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.
Je dois aussi pouvoir charger un bâtiment unique par son identifiant

**Comment by crenny35** [comment]
Disponible en integration

**Comment by cbriand** [comment]
OK, ça fonctionne
