### ISSUE TITLE
B4.a - Streaming - Mobilier urbain - données 2D

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#33]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger les données mobilier urbain. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir données 2D du mobilier urbain. 
Les trois niveaux de filtre géographique suivants doivent être utilisables : Bbox, commune, quartier.

**Comment by crenny35** [comment]
Avons nous les entrants pour commencer cette tache ?

**Comment by cbriand** [comment]
Non, le service WFS n'existe pas encore. Je relance mes collègues sur ce point.

**Comment by cbriand** [comment]
En attendant que le service WFS existe vraiment, on peut faire pointer le code vers le WFS de la végétation générique (https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9). Merci de nous expliquer comment attribuer la bonne redirection une fois que le service WFS sera fonctionnel.

**Comment by cbriand** [comment]
Le service n'est pas fonctionnel et ne retourne aucun résultat. 
Le fichier rendu fait état d'une exception levée sur un paramètre invalide.

`<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows https://public.sig.rennesmetropole.fr/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="InvalidParameterValue" locator="typeName">
<ows:ExceptionText>Feature type :undefined unknown</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>`

**Comment by crenny35** [comment]
Es tu sur qu'il ne s'agissait pas d'une indisponibilité coté geoserver ? la requete suivante me renvoie des résultats : 
https://api3d.imfr.cgi.com/recette/api/collections/mobilier/items?bbox=1351534.8845,7223500.0490,1354849.5635,7225175.6015

**Comment by cbriand** [comment]
OK pour le service, par contre, il faudrait un nom de fichier plus parlant que wfs.json. Par exemple : street_furniture.json

**Comment by crenny35** [comment]
Changement effectué

**Comment by cbriand** [comment]
OK, validé
