### ISSUE TITLE
B3.b - Streaming - Végétation - catalogue de représentation 3D

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#34]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger le catalogue de représentation 3D de la végétation. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir toutes les représentations possibles de végétation. 
Aucun filtre géographique n'est demandé.

**Comment by cbriand** [comment]
Fichier : https://3d.sig.rennesmetropole.fr/ressources/3d_rennesmetropole_bibli_arbres.zip

**Comment by crenny35** [comment]
Bonjour Cédric, il s'agit d'un fichier à ajouter sur la page de téléchargement ? Si oui, il nous faudrait le lien public vers les métadonnées.

**Comment by cbriand** [comment]
Oui, c'est bien ça, mais la page de métadonnées n'existe pas encore. Je relance mes collègues sur ce point.

**Comment by cbriand** [comment]
La page de métadonnées à utiliser est celle-ci : https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9

**Comment by cbriand** [comment]
OK, validé
