### ISSUE TITLE
B4.b - Streaming -Mobilier urbain - catalogue de représentation 3D

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#35]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger le catalogue de représentation 3D du mobilier urbain. 

Pour valider cette API, je dois pouvoir me connecter au flux correspondant obtenir toutes les représentations possibles du mobilier urbain. 
Aucun filtre géographique n'est demandé.

**Comment by cbriand** [comment]
Fichier : https://3d.sig.rennesmetropole.fr/ressources/3d_rennesmetropole_bibli_mobilier_urbain.zip

**Comment by crenny35** [comment]
Bonjour Cédric, il s'agit d'un fichier à ajouter sur la page de téléchargement ? Si oui, il nous faudrait le lien public vers les métadonnées.

**Comment by cbriand** [comment]
Oui, c'est bien ça, mais la page de métadonnées n'existe pas encore. Je relance mes collègues sur ce point.

**Comment by cbriand** [comment]
En attendant que la page de métadonnées du mobilier urbain existe, on peut faire pointer notre entrée vers la page de métadonnées de la végétation générique (https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9).
Merci de nous expliquer comment rétablir le lien vers la bonne métadonnées quand la page existera.

**Comment by crenny35** [comment]
La façon dont on a implémenté nous empêche ne mettre deux blocs pointant sur la même metadata.

**Comment by cbriand** [comment]
Ok, je vais demander la construction de la nouvelle page de métadonnées alors

**Comment by cbriand** [comment]
Page de métadonnées créée : https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/f54c36c1-823a-421f-a305-84895b731798

**Comment by cbriand** [comment]
Cette entrée en téléchargement n'est pas intégrée dans la release 0.4.10

**Comment by crenny35** [comment]
Mise a jour du fichier deploy env sur l'environnement de recette.

**Comment by cbriand** [comment]
OK, validé
