### ISSUE TITLE
Page téléchargement

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#37]
En tant qu'utilisateur de l'API 3D, je souhaite pouvoir consulter une page web qui liste les fichiers téléchargeables.

Pour valider cette page, je dois pouvoir ouvrir la page qui liste les fichiers en téléchargement, et consulter individuellement les métadonnées de chacun des fichiers téléchargeables.
Je dois aussi pouvoir être redirigé vers le swagger de l'API (flux).

**Comment by cbriand** [comment]
**Recette du 17/06/2022**
- Il manque les mentions légales
- Quel est l'objet du bloc de texte sous "API 3D" (actuellement Lorem Ipsum) ?
- Le libellé "API 3D" doit bien devenir le lien vers la page swagger ?

**Comment by crenny35** [comment]
Remarque prise en compte, nouvelle version disponible sur l'environnement de recette.

**Comment by cbriand** [comment]
deux petits ajustements complémentaires : 
- lien vers le swagger : le faire ouvrir dans un onglet différent (target=_blank)
- mettre un espace vide entre le dernier point d'entrée et les mentions légales et réduire la police des mentions légales pour que les mentions légales n'attirent pas plus l'attention que les points d'entrées
