### ISSUE TITLE
B1 - Streaming - Le fichier raster obtenu n'est pas conforme au MNT source

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#49]
En regardant les fichiers obtenus par des requêtes comme  https://api3d.imfr.cgi.com/recette/collections/raster/coverage/tiles?codeInsee=35081

On s'aperçoit que tous les fichiers font 510 ko ce qui est aberrant.
En diagnostiquant avec GDAL on s'aperçoit que tous les fichiers font la même taille : ` 678, 768` et ont donc des taille de pixels qui ne respecte pas le MNT. Ex : `Pixel Size = (4.235988200589970,-3.371093750000000)`

Rappel : le MNT 2018 a une résolution de 50 cm.

La requête WMS getMap est élaborée ici : https://github.com/sigrennesmetropole/api-3D/blob/7c032a2612b02da2ed23c572ef471cbd52ef289b/src/clients/geoserver/wms.js#L18-L29

et appelée depuis ici : https://github.com/sigrennesmetropole/api-3D/blob/7c032a2612b02da2ed23c572ef471cbd52ef289b/src/services/DataService.js#L73

Dans cette dernière ligne on voit bien que les paramètres `WIDTH` et `HEIGHT` sont en dur alors qu'ils doivent être calculés dynamiquement en fonction de l'emprise (la bbx) demandée. **Il faut en effet restituer pour toute requête une image à la résolution du MNT 2018 soit 0,5 m.**
il faut donc calculer la largeur et la hauteur de la bbox en unité terrain et multiplier par 2 pour obtenir la largeur et la hauteur de l'image à générer.

Exemple :

![image](https://user-images.githubusercontent.com/6370443/175965970-d70ce723-36c0-4145-b3b6-04a256864c71.png)

Il nous semble important d'avoir quelque part dans la configuration une déclaration du "produit" MNT et de sa résolution. Afin d'avoir qqch de dynamique pour cet algo. Créer une issue pour cette demande ?

**Comment by anthalcgi** [comment]
Il n'y pas assez de mémoire allouée pour permettre les requêtes volumineuses. Il faudrait 5 GB (plus précisément 4,787109 GB) pour télécharger l'entièreté du mnt, or la limite est fixée à 65,536 MB. Il faudrait paramétrer le service WMS du geoserver pour allouer plus de mémoire.

**Comment by MaelREBOUX** [comment]
OK : je comprend mieux. 

Voici un getmap pour une surface de 9,6 km²

https://public.sig.rennesmetropole.fr/geoserver/raster/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fgeotiff&LAYERS=raster%3Amnt2018&SRS=EPSG%3A3948&STYLES=&WIDTH=6200&HEIGHT=6200&BBOX=1344797%2C7212280%2C1347897%2C7215380

La réponse du GeoServer est : `Rendering request would use 112617KB, whilst the maximum memory allowed is 65536KB `

**Comment by MaelREBOUX** [comment]
OK. Le changement de configuration sera fait entre le 18/08 et le 20/08. Normalement.

**Comment by MaelREBOUX** [comment]
Je confirme que la requête plus haut passe nickel. Je récupère un fichier de 37 Mo environ.

Et le fichier me semble conforme à nos attentes. Quid S ANDRU ?

```
gdalinfo.exe raster-mnt2018.tif
Driver: GTiff/GeoTIFF
Files: raster-mnt2018.tif
Size is 6200, 6200
Coordinate System is:
PROJCRS["RGF93 / CC48",
    BASEGEOGCRS["RGF93",
        DATUM["Reseau Geodesique Francais 1993",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4171]],
    CONVERSION["France Conic Conformal zone 7",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",48,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",3,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",47.25,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",48.75,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",1700000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",7200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["France - mainland - 47┬░N to 49┬░N"],
        BBOX[47,-4.87,49,8.23]],
    ID["EPSG",3948]]
Data axis to CRS axis mapping: 1,2
Origin = (1344797.000000000000000,7215380.000000000000000)
Pixel Size = (0.500000000000000,-0.500000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_XRESOLUTION=1
  TIFFTAG_YRESOLUTION=1
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 1344797.000, 7215380.000) (  1d46' 0.84"W, 48d 2'22.32"N)
Lower Left  ( 1344797.000, 7212280.000) (  1d45'51.60"W, 48d 0'42.14"N)
Upper Right ( 1347897.000, 7215380.000) (  1d43'31.45"W, 48d 2'28.50"N)
Lower Right ( 1347897.000, 7212280.000) (  1d43'22.28"W, 48d 0'48.31"N)
Center      ( 1346347.000, 7213830.000) (  1d44'41.54"W, 48d 1'35.32"N)
Band 1 Block=6200x16 Type=Byte, ColorInterp=Gray
  NoData Value=0
```

**Comment by MaelREBOUX** [comment]
On valide : le fichier obtenu est conforme.
