### ISSUE TITLE
A2 - Terrain en raster d'élévation sans texture

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#5]

**Comment by cbriand** [comment]
En tant qu'utilisateur de l'API 3D, je souhaite télécharger le terrain en raster d'élévation.

Pour valider cette API, je dois pouvoir recevoir localement le fichier téléchargé représentant le terrain maillé au format TIN. L'intégrité du fichier doit pouvoir être vérifiée avec sa clé sha-1.

**Comment by cbriand** [comment]
**Recette du 17/06/2022**
- Retranscription des informations OK
- Le téléchargement du fichier n'est pas activé

**Comment by crenny35** [comment]
Fichier uploadé pour être disponible en téléchargement

**Comment by cbriand** [comment]
OK, validé
