### ISSUE TITLE
B1 + B2 - Streaming - Pourquoi 4 paramètres BBOX ?

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#51]
Suite au test de ce jour vous avez indiqué que le paramétrage d'une bbox se fait en spécifiant 4 fois ce paramètre, dans l'ordre suivant :

- min X
- min Y
- max X
- max Y

Ce qui donne une URL de ce type : `/collections/buildings/items?f=application%2Fjson&bbox=1345455&bbox=7212910&bbox=1347264&bbox=7213959&texture=non`

Cette façon de faire est déroutante car dans le monde géomatique et OGC on n'a traditionnellement qu'un seul paramètre BBOX avec des valeurs séparées par des virgules. 

Exemple getMap WMS : https://public.sig.rennesmetropole.fr/geoserver/raster/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/geotiff&LAYERS=mnt2018&CRS=EPSG%3A3948&BBOX=1345554,7212816,1347904,7214175&WIDTH=4700&HEIGHT=2718

Pourriez-vous SVP garder cette logique "métier" ?
Car sinon  4 paramètres = 4 noms différents me semblerait plus logique.

**Comment by cbriand** [comment]
Classiquement, on attends une seule valeur string (et non pas un tableau) renseigné par 4 coordonnées séparées par des virgules

**Comment by cbriand** [comment]
OK. validé
