### ISSUE TITLE
B1 + B2 - Streaming - Documentation du paramétrage de la BBOX

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#52]
Quand on arrive sur le swagger on n'a aucune information sur comment on doit utiliser les paramètres bbox.

Il faut compléter la description du swagger.

Attention : à lier avec #51

**Comment by cbriand** [comment]
Indiquer qu'il est attendu un champ de type string qui présente les coordonnées xmin, ymin, xmax, ymax séparées par des virgules (avec un exemple)

**Comment by cbriand** [comment]
OK validé
