### ISSUE TITLE
B2 - Streaming - Buildings - Manque filtrage sur code INSEE

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#53]
Il manque le filtrage sur code INSEE conformément aux spécifications.

Même principe que pour le MNT 2018 : utiliser le fichier `src/services/bbox_codeinsee.json`

**Comment by cbriand** [comment]
OK, validé avec les URLs 
 - https://api3d.imfr.cgi.com/recette/collections/buildings/items?f=application%2Fjson&codeInsee=35001&texture=non
 - https://api3d.imfr.cgi.com/recette/collections/buildings/items?f=application%2Fjson&codeInsee=35001&texture=oui

**Comment by cbriand** [comment]
Ticket à valider sur plateforme RM avec les données de plusieurs communes

**Comment by cbriand** [comment]
à lier au ticket #65 qui explique comment doit être interprété le filtre code insee sur les buildings  (différent du mnt car on ne doit pas utiliser le fichier de correspondance commune/bbox)
