### ISSUE TITLE
A* - Téléchargement - manque un lien de retour vers la métadonnée source

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#54]
Dans le mon des IDG, une bonne pratique et de proposer un lien permettant de remonter vers la métadonnée originale dans le catalogue source.

Quelque chose dans ce style ?

![image](https://user-images.githubusercontent.com/6370443/175973864-b465f18a-4c60-4dc6-aae3-b4a0e15530cf.png)

Avec une url vers la MD genre https://public.sig.rennesmetropole.fr/geonetwork/srv/fre/catalog.search#/metadata/3faad540-1cc3-4224-a326-2bf1e8f550bc

**Comment by MaelREBOUX** [comment]
Testé ce jour : nickel sauf... que ce serait mieux que cela s'ouvre dans un nouvel onglet / nouvelle fenêtre.

**Comment by cbriand** [comment]
OK, validé
