### ISSUE TITLE
B1 + B2 - Streaming - Vérifier filtrage bbox sur test surface

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/api-3D#56]
Nous n'avons pas réussi à récupérer des données par BBOX car on obtient systématiquement une erreur 400 qui indique que la BBOX concerne une superficie supérieure à 10 km².

Pouvez-vous vérifier SVP ?

**Comment by MaelREBOUX** [comment]
Je confirme le problème. Ci-dessous une requête qui correspond à une emprise de 9,6 km² et on obtient une erreur 400.

https://api3d.imfr.cgi.com/recette/collections/raster/coverage/tiles?bbox=1344797&bbox=7212280&bbox=1347897&bbox=7215380

**Comment by MaelREBOUX** [comment]
la même sur les bâtiments

https://api3d.imfr.cgi.com/recette/collections/buildings/items?f=application%2Fjson&bbox=1344797&bbox=7212280&bbox=1347897&bbox=7215380

**Comment by anthalcgi** [comment]
J'avais laissé un commentaire à ce sujet il y a une semaine mais j'ai l'impression qu'il a disparu 😶
Le problème vient de la mémoire allouée au flux WMS côté geoserver. 

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "https://public.sig.rennesmetropole.fr/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      Rendering request would use 4787109KB, whilst the maximum memory allowed is 65536KB
Details:
org.geoserver.platform.ServiceException: Rendering request would use 4787109KB, whilst the maximum memory allowed is 65536KB`

La mémoire allouée actuellement est de 65 MB alors qu'il faudrait environs 5 GB pour charger le mnt dans son entièreté.
Le problème devrait se régler une fois le paramétrage effectué.

**Comment by anthalcgi** [comment]
Effectivement c'est une confusion de ma part 😅
La source du problème est identifiée, on teste et on revient vers vous.

**Comment by MaelREBOUX** [comment]
testé avec https://api3d.imfr.cgi.com/recette/collections/buildings/items?f=application%2Fjson&bbox=1361199.4152829673&bbox=7223153.675913142&bbox=1366679.9160615348&bbox=7227752.758572863&texture=non

on valide.
