### ISSUE TITLE
Mauvais usage du filtre codeInsee sur plusieurs entrées

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#65]
Sur plusieurs entrées de l'API, il est possible de restreindre les résultats avec le paramètre codeInsee.
Il existe une table de correspondance entre codeInsee et bbox. Cette table de correspondance n'est utile que pour l'entrée /collections/mnt2018/coverage pour laquelle il est attendu en retour une emprise rectangulaire du mnt qui couvre le territoire complet de la commune. Attention, le paramètre BBOX_MAX_SIZE n'entre pas en jeu lorsque le filtre sur code insee est utilisé (on l'utilise uniquement sur le filtre bbox explicite).

Pour les autres entrées de l'API (/collections/buildings/items, collections/added_buildings/items, etc.), il ne faut pas utiliser cette correspondance entre codeInsee et BBox pour éviter de récupérer des bâtiments d'une commune limitrophe.
Le filtre codeInsee doit restreindre les résultats par leur identifiant qui porte l'information de code Insee. La recette RM ne fonctionnant pas, je ne peux qu'observer les logs où j'observe une transcription du codeInsee en bbox sur l'entrée /collections/buildings/items
<pre>{"level":"info","message":"Appel du path /collections/buildings/items","parametres":{"codeInsee":"35001","f":"application/json","texture":"oui"},"service":"user-service","timestamp":"2022-09-02T08:28:45.677Z"}
info: Appel du path /collections/buildings/items {"parametres":{"codeInsee":"35001","f":"application/json","texture":"oui"},"service":"user-service","timestamp":"2022-09-02T08:28:45.677Z"}
error: Command failed: /etc/3DCityDB-Importer-Exporter-5.1.1/bin/impexp export --db-host=localhost --db-port=5432 --db-name=3dcitydb --db-username=app_api --db-password="Za&'N@Lc^j**ta&CbxYl" -o /usr/src/app/src/export/e39e9edc-d212-42a1-bf30-fba6eae3aee1.zip --compressed-format=cityjson --bbox=1360146,7222983,1367747,7229055
</pre>

Nous attendons un filtre SQL du type 
SELECT cityobject_id
FROM citydb.cityobject_genericattrib
WHERE attrname='BUILDINGID' and strval LIKE '35001_%'

**Comment by cbriand** [comment]
Même problème rencontré que sur les batiments ajoutés ou supprimés, la requête n'est pas acceptée parce que le nom du schéma qui porte la table n'est pas précisé dans la requête : 
`--sql-select="SELECT cityobject_id FROM cityobject_genericattrib WHERE attrname='BUILDINGID' and strval LIKE '35001_%'"
[15:12:58 ERROR] Failed to query the database.
[15:12:58 ERROR] Caused by: org.postgresql.util.PSQLException: ERREUR: la relation « cityobject_genericattrib » n'existe pas
  Position: 222
`

La rquête attendue serait plutôt 
`SELECT cityobject_id FROM citydb.cityobject_genericattrib WHERE attrname='BUILDINGID' and strval LIKE '35001_%'`

**Comment by crenny35** [comment]
Version 0.4.3 déployée en recette.

**Comment by cbriand** [comment]
La release 0.4.3 régresse et transforme le code insee en bbox au lieu de lancer le filtre sur le BUILDINGID

**Comment by cbriand** [comment]
OK, ça fonctionne très bien.
