### ISSUE TITLE
Plantage swagger sur retour zip

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#66]
Swagger plante lorsqu'on teste la route /collections/buildings/items avec texture (zip retourné).

Après avoir lancé la commande, un loader apparait, mais la page plante systématiquement au bout d'un moment.

![image](https://user-images.githubusercontent.com/38095778/188477497-c362bd53-c1ea-476d-9d2b-c536dbf8f2d7.png)

**Comment by cbriand** [comment]
En ce moment, tous les tests sur l'entrée /collections/buildings/items/ de la page swagger plantent (alors que les tests par url fonctionnent).

**Comment by cbriand** [comment]
A lier au ticket #65

**Comment by crenny35** [comment]
Bonjour,
Swagger ne permet pas d'afficher le résultat sous forme de zip. Pour vérifier le fonctionnement, vous pouvez coller la "request url" générée au dessus du code retour dans un nouvel onglet de navigateur.

**Comment by cbriand** [comment]
Oui, mais ce que je demande, ce n'est pas de pouvoir tester le retour de l'API, mais c'est que la page swagger ne plante pas si on entre dans des conditions difficiles pour swagger.
Par exemple, ici, la page se bloque, et on ne peut plus rien faire sur cet écran (même copier-coller la "request url")

**Comment by crenny35** [comment]
J'ai fait une modification pour pouvoir télécharger le résultat de la requête en cas de retour fichier sur swagger. La popup "ne répond pas" c'est un comportement car nous sommes en traitement synchrone. En fonction du temps de réponse, il faudra appuyer sur attendre.

**Comment by cbriand** [comment]
OK sur votre plateforme de recette, mais pas dans notre environnement. Est-ce que cette évolution nécessite un nouveau paramétrage ?

**Comment by crenny35** [comment]
Est ce que ça ne vient pas du fait que vous avez plus de données sur votre environnement et qu'il faut attendre plus longtemps ? as tu essayé en renseignant une limite ?

**Comment by cbriand** [comment]
Plusieurs essais aujourd'hui : 
le système fonctionne bien pour les retours tif du mnt et les retours zip des bâtiments texturés, par contre ça ne fonctionne plus du tout pour les demandes non texturées (fichier cityjson ou cityGML).

**Comment by crenny35** [comment]
Je viens d'essayer en pointant vers la prod et en mettant une limite dans le nombre de résultats, ça semble fonctionner.
https://api-3d.sig.rennesmetropole.fr/collections/buildings/items?f=application%2Fjson&limit=20&texture=non
Je pense que pour tester des gros volumes, il ne faut pas passer par swagger.

**Comment by cbriand** [comment]
Ta requête n'est pas pertinente parce qu'il manque la restriction géographique (cf. #71).

Ici, il y a une regression avec la page swagger quand on filtre la recherche de bâtiments sur code_insee (exemple 35001).
Si la texture est demandée : résultat OK avec le nouveau système de fichier téléchargeable (121 167 Ko)
Si la texture n'est pas demandée  : résultat KO, le swagger plante systématiquement alors que ça fonctionnait avec les précédentes releases. En chargeant le résultat par curl, le fichier json obtenu pèse 14 217 Ko, soit 8 fois moins lourd que le fichier obtenu en demandant la texture.

Si on se met à la place de l'utilisateur, on ne peut pas accepter le plantage de la page swagger plante (qui devient totalement inutilisable) sur certaines entrées.

**Comment by cbriand** [comment]
OK, cette solution me convient

**Comment by cbriand** [comment]
La solution a-t-elle bien été intégrée dans la dernière release (0.4.8) ? Le swagger plante toujours dès qu'on lance une requête de batiments non texturés (même sur une toute petite bbox).

**Comment by crenny35** [comment]
C'est une régression suite à la carte expérience utilisateur qui ajoutait /api au début du path. Je prépare une nouvelle version.

**Comment by cbriand** [comment]
Ca marche bien. Validé
