### ISSUE TITLE
Gérer l'extraction mnt sans filtre saisi

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#72]
Sur l'entrée /collections/mnt2018/coverage, obliger la saisie d'un filtre geographique (bbox ou codeInsee). Si aucun des deux n'est saisi, alors générer une erreur.

**Comment by anthalcgi** [comment]
Actuellement, le comportement par défaut est de lancer le téléchargement de tout le mnt. Après avoir résolu cette issue, l'utilisateur devra-t-il toujours être capable de télécharger tout le mnt en renseignant la bbox `1330000, 7203000, 1368000, 7246000`, ou faut-il aussi mettre une limite à la taille de la bbox ?

**Comment by cbriand** [comment]
En cas de manquement des deux paramètres, une erreur 400 (Bad request error) semble la plus adaptée

**Comment by crenny35** [comment]
Actuellement, nous renvoyons le code d'erreur 400 Bad Request avec un Json comme celui ci:
{
  "description": "Invalid input : <bbox> or <code insee> must be set",
  "code": 400
}
ce Json permet à l'utilisateur de savoir pourquoi sa requête est incorrecte. Veux tu qu'on enlève la description de chaque erreur 400 et qu'on la remplace par "BadRequest" ?

**Comment by cbriand** [comment]
La description de l'erreur est une bonne pratique. On laisse comme ça.

**Comment by cbriand** [comment]
OK, validé
