### ISSUE TITLE
collections/mnt2018/coverage : Lancer une erreur si la bbox est out of bounds ?

### ISSUE THREAD

**Issue by anthalcgi** [sigrennesmetropole/api-3D#73]
Actuellement, si l'utilisateur renseigne une bbox qui est disjointe (prédicat _disjoint_) de la bbox du mnt, la requête est validée (code 200) et une image blanche est téléchargée.
Lorsque la bbox renseignée recouvre (prédicat _overlap_) en partie la bbox du mnt, alors les données de la partie recouverte apparaissent dans le raster en sortie, et le reste des pixels restent blancs.

Il s'agit du comportement attendu lors de ce cas de figure selon les specs du WMS de l'OCG ([PDF](https://portal.ogc.org/files/?artifact_id=14416), section 7.3.3.6).

Doit-on conserver ce comportement ou doit-on lancer une erreur 400 si la bbox renseignée est disjointe et/ou recouvre la bbox du mnt ?

**Comment by cbriand** [comment]
Non, pas d'erreur personnalisée. Le comportement actuel est correct. C'est au client de s'assurer qu'il tape bien sur l'emprise de la donnée.

**Comment by anthalcgi** [comment]
Ok, dans ce cas je ferme l'issue.
