### ISSUE TITLE
Wiki - renseigner la partie 7 - ajout d'un point d'entrée API

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#85]
Remplir la partie 7 du wiki pour expliquer la procédure d'ajout d'un point d'entrée.
En profiter pour expliquer comment l'image docker est créée à partir d'une release pour pouvoir être déployée sur serveur.

**Comment by crenny35** [comment]
la création de l'image docker est expliqué déjà dans :
https://github.com/sigrennesmetropole/api-3D/wiki#46-cr%C3%A9ation-dune-release
https://github.com/sigrennesmetropole/api-3D/wiki#47-g%C3%A9n%C3%A9rer-une-nouvelle-image-docker

Je vais faire la partie 7 en essayant de détailler au mieux.

**Comment by cbriand** [comment]
Ca me semble suffisant. Merci
