### ISSUE TITLE
Image docker de la branche develop non fonctionnelle

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#91]
L'image docker déployée sur le serveur RM n'est plus fonctionnelle.
Le site déployé sur la plateforme de test ne retourne que l'information suivante 
{"f":"application/json"}

![image](https://user-images.githubusercontent.com/38095778/198539141-f2a90e1b-d99c-4900-9292-8cf8f1a6baff.png)

**Comment by crenny35** [comment]
L'image dévelop date de 16 jours soit je pense avant la carte expérience utilisateur ( la page de téléchargement se trouve sur /telechargement). je vais builder une nouvelle image develop. Est ce que vous voulez que le build de develop se fasse a chaque fois qu'il y a un commit sur la branche ?

**Comment by cbriand** [comment]
Oui, ce serait super si un build pouvait être lancé à chaque commit 
Il faut penser à apporter cette précision dans la documentation wiki.

**Comment by crenny35** [comment]
Est ce que tu as essayé cette commande pour mettre a jour l'image :
 docker pull ghcr.io/sigrennesmetropole/api-3d:develop

**Comment by cbriand** [comment]
Oui, c'est bien la commande qu'il me manquait. Je mets à jour le wiki pour apporter cette précision
