### ISSUE TITLE
Partition /var qui grossit jusqu'à saturer le serveur

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#94]
A l'usage de l'API, les conteneurs docker grossissent jusqu'à peser 126Go au lieu de 3.7Go au démarrage.
Une commande "docker compose down" puis "docker compose up" permet de récupérer l'espace disque.
Nous soupçonnons une production de cache qui ne se vide jamais.

Le problème de saturation impacte la base de données et une reconstruction du conteneur lui affecte de nouvelles adresses IP qu'il faut déclarer dans le pg_hba.conf pour autoriser la consultation des données.

**Comment by crenny35** [comment]
@cbriand, je pense que le soucis venait des fichiers zip texturés qui n'était pas supprimé. on pourrait vérifier ensemble si c'est fichiers sont bien présent dans le conteneur docker. Si c'est ça je ferais la merge request de la correction.

**Comment by crenny35** [comment]
@cbriand je pense que ça vient du yaml dans liste déroulante serveur il n'y a que le serveur de production. Du coup quand tu lances l'action il lance sur l'url https://api-3d.sig.rennesmetropole.fr/api au lieu de https://api-3d-test.sig.rennesmetropole.fr/api. 
Du coup l'action se lance sur le conteneur de production qui n'a pas le code a jour. Est ce que dans swagger dans la partie réponse dans le champ Request URL tu vois le nom du serveur de production ou de test ?
si c'est le serveur de production, on peut soit ajouter le serveur de test dans la liste déroulante, soit tu copies l'url dans un nouvel onglet et tu changes par l'url de test.

**Comment by cbriand** [comment]
Tu as raison. En testant les bonnes url, j'observe bien le bon comportement et la disparition des fichiers générés.
Tu peux merger cette évolution dans la branche master.

Pour le yaml qui liste les serveur, l'idéal serait d'avoir un yaml différent par environnement (ou branche) => ce serait possible ?

**Comment by crenny35** [comment]
@cbriand j'ai mergé dans la branche master. est ce que j'attend le traitement de la dernière carte avant de faire une release ?

**Comment by crenny35** [comment]
Pour le Yaml, il faudrait tester de mettre /api dans le yaml au lieu de l'url complète vu qu'il y a un nom de domaine différent pour le serveur de test et de prod cela devrait marcher.
