### ISSUE TITLE
Appel du protocole WCS sur le MNT

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/api-3D#96]
Le service WCS des geoservers du SIG peut être utilisé pour le MNT. 

Une requête-type est de la forme suivante où seule le paramètre BBOX serait variable via l'API.
https://public.sig.rennesmetropole.fr/geoserver/raster/ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&coverage=mnt2018&CRS=EPSG:3948&BBOX=1358176.6,7224937.93,1361809,7227797.4&WIDTH=8162&HEIGHT=6374&format=image/geotiff

**Comment by crenny35** [comment]
@cbriand, est ce qu'il s'agit d'un nouveau point d'entrée ou bien faut il appeler le geoserver avec le nouveau protocole en remplacement de WFS

**Comment by crenny35** [comment]
@cbriand, Pour être sur de faire la bonne chose, le WFS est appelé uniquement pour le mobilier et la végétation. Est ce que je remplace ce qui est fait actuellement pour le mobilier et la végétation : 
`let url = 'https://public.sig.rennesmetropole.fr/geoserver/ows?request=GetFeature&service=WFS'
            + '&version=' + version
            + '&typeName=' + typeName
            + '&bbox=' + bbox.toString().replace(/,/g,"%2C")
            + '&srs=' + srs
            + '&outputFormat=' + f;`
par 
`let url = 'https://public.sig.rennesmetropole.fr/geoserver/ows?request=GetFeature&service=WCS'
            + '&version=' + version
            + '&typeName=' + typeName
            + '&bbox=' + bbox.toString().replace(/,/g,"%2C")
            + '&srs=' + srs
            + '&outputFormat=' + f;`

Ou bien il s'agit du remplacement de l'appel pour le mnt (/collections/mnt2018/coverage) qui est actuellement : 
` let url = 'https://public.sig.rennesmetropole.fr/geoserver/raster/wms?service=WMS'
            + '&version=' + version
            + '&request=GetMap'
            + '&layers=' + workspace + '%3A' + layers
            + '&bbox=' + bbox.toString().replace(/,/g,"%2C")
            + '&width=' + witdh
            + '&height=' + height
            + '&srs=' + srs
            + '&format=' + format;`
par:
` let url = 'https://public.sig.rennesmetropole.fr/geoserver/raster/ows?SERVICE=WCS'
            + '&version=' + version
            + '&request=GetCoverage'
            + '&coverage=mnt2018'
            + '&bbox=' + bbox.toString().replace(/,/g,"%2C")
            + '&width=' + witdh
            + '&height=' + height
            + '&CRS=' + crs
            + '&format=' + format;`

**Comment by cbriand** [comment]
Le protocole WCS ne s'applique qu'aux flux de type coverage, soit uniquement le mnt dans notre cas. Il ne faut absolument pas remplacer les flux WFS qui sont corrects.

**Comment by crenny35** [comment]
@cbriand, depuis ce matin quand j'appel l'url que tu m'as fourni, il me retourne une image blanche. je ne peux pas tester l'intégration de mon coté.

**Comment by cbriand** [comment]
Ouvert dans un éditeur d'image du style Gimp, l'image est blanche, par contre, si tu la déposes dans un projet QGIS, ça fonctionne bien. C'est certainement du au format géoréférencé geotiff

**Comment by cbriand** [comment]
Ca fonctionne très bien. On peut merger en master
